In [1]:
import numpy as np

In [4]:

x= np.array([[1.2, 1.5, 1.8],
[1.3, 1.4, 1.9],
[1.1, 1.6, 1.7]])
y = np.array([5, 10, 9]).T

In [5]:
x

array([[1.2, 1.5, 1.8],
       [1.3, 1.4, 1.9],
       [1.1, 1.6, 1.7]])

In [6]:
y

array([ 5, 10,  9])

In [12]:
z=x*y
z

array([[ 6. , 15. , 16.2],
       [ 6.5, 14. , 17.1],
       [ 5.5, 16. , 15.3]])

In [29]:
%%timeit
z.sum(axis=1)

1.84 µs ± 37.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [30]:
z.sum(axis=1)

array([37.2, 37.6, 36.8])

In [39]:
x[[0,1]]

array([[1.2, 1.5, 1.8],
       [1.3, 1.4, 1.9]])

In [17]:
len(x)

3

In [20]:
x.shape

(3, 3)

In [36]:
x[(1,2)]

1.9

In [42]:
for i in range(3):
    print(x[i]*y)

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]


In [45]:
%%timeit
for i in range(3):
    print(x[i]*y)

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.

[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.

[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.

[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.

[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.

[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.

[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.

[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.

[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.

[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
[ 6.  15.  16.2]
[ 6.5 14.  17.1]
[ 5.5 16.  15.3]
753 µs ± 49.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
