In [1]:
import numpy as np

In [2]:
np.random.seed(1)
X = np.random.randint(1, 10, size=30)

In [3]:
X

array([6, 9, 6, 1, 1, 2, 8, 7, 3, 5, 6, 3, 5, 3, 5, 8, 8, 2, 8, 1, 7, 8,
       7, 2, 1, 2, 9, 9, 4, 9])

In [4]:
X=X.reshape(-1,3)

In [5]:
X

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3],
       [5, 6, 3],
       [5, 3, 5],
       [8, 8, 2],
       [8, 1, 7],
       [8, 7, 2],
       [1, 2, 9],
       [9, 4, 9]])

In [6]:
X[:,-1]<=3

array([False,  True,  True,  True, False,  True, False,  True, False,
       False])

In [7]:
X[X[:,-1]<=3,-1]=0

In [8]:
X

array([[6, 9, 6],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 5],
       [8, 8, 0],
       [8, 1, 7],
       [8, 7, 0],
       [1, 2, 9],
       [9, 4, 9]])

In [9]:
X[((X[:,-1]>3)&(X[:,-1]<=6)),-1]=1

In [10]:
X

array([[6, 9, 1],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 1],
       [8, 8, 0],
       [8, 1, 7],
       [8, 7, 0],
       [1, 2, 9],
       [9, 4, 9]])

In [12]:
X[X[:,-1]>6,-1]=2

In [13]:
X

array([[6, 9, 1],
       [1, 1, 0],
       [8, 7, 0],
       [5, 6, 0],
       [5, 3, 1],
       [8, 8, 0],
       [8, 1, 2],
       [8, 7, 0],
       [1, 2, 2],
       [9, 4, 2]])

In [19]:
X_trai=X[:,:2]

In [20]:
X_trai

array([[6, 9],
       [1, 1],
       [8, 7],
       [5, 6],
       [5, 3],
       [8, 8],
       [8, 1],
       [8, 7],
       [1, 2],
       [9, 4]])

In [28]:
y_train=X[:,-1]

In [29]:
y_train

array([1, 0, 0, 0, 1, 0, 2, 0, 2, 2])

# 分类为1的样本

In [31]:
y_train==1

array([ True, False, False, False,  True, False, False, False, False,
       False])

In [32]:
X_trai[y_train==1]

array([[6, 9],
       [5, 3]])

# 分类为0的样本

In [33]:
X_trai[y_train==0]

array([[1, 1],
       [8, 7],
       [5, 6],
       [8, 8],
       [8, 7]])

# 分类为2的样本

In [34]:
X_trai[y_train==2]

array([[8, 1],
       [1, 2],
       [9, 4]])