In [1]:
import numpy as np


In [2]:
idx =np.arange(1,5).reshape(2,-1)

In [3]:
idx

array([[1, 2],
       [3, 4]])

In [5]:
a=np.arange(16).reshape(4,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
row=[0,1,3]

In [7]:
col=[1,2,3]

In [8]:
a[row,col]

array([ 1,  6, 15])

In [11]:
x= np.arange(10)

In [12]:
x>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [13]:
x[x>5]

array([6, 7, 8, 9])