In [1]:
import numpy as np
import matplotlib.pyplot as plt
import struct
from ML.knn import KNeighborsClassifier
from ML.model_selection import train_test_split
from collections import Counter
from ML.metrics import accuracy_score

## 1、导入数据集

In [2]:
X = np.load('digits_images.npy')

In [3]:
X.shape

(1797, 64)

In [4]:
y = np.load('digits_lable.npy')

In [5]:
y.shape

(1797,)

In [6]:
y[:3]

array([0, 1, 2], dtype=int64)

## 2、拆分数据

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,0.1,1)

In [8]:
X_train.shape

(1618, 64)

In [9]:
y_train.shape

(1618,)

In [10]:
X_test.shape

(179, 64)

In [11]:
y_test.shape

(179,)

## 3、训练算法

In [12]:
clf = KNeighborsClassifier()

In [13]:
clf.fit(X_train,y_train)

In [14]:
y[:3]  # 简单验证

array([0, 1, 2], dtype=int64)

In [15]:
clf.predict(X[:3])

array([0, 1, 2], dtype=int64)

In [16]:
clf.score(X_test,y_test)  # 评分

1.0

## 4、最佳超参数测试

In [17]:
best_score = 0
best_k = 0
best_p=0
# 双重循环遍历最佳值
for k in range(1,10):
    for p in range(1,5):
        clf = KNeighborsClassifier(k=k,p=p)        
        clf.fit(X_train,y_train)
        score = clf.score(X_test,y_test)
        if (score>best_score):
            best_score = score
            best_k = k
            best_p = p

In [18]:
print('best_k',best_k)
print('best_score',best_score)
print('best_p',p)

best_k 3
best_score 1.0
best_p 4
